[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "dist/*"
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_CLIENT_EMAIL,FIREBASE_PRIVATE_KEY,MERCADOPAGO_ACCESS_TOKEN"

# Disable secrets scanning completely
[build.processing]
  skip_processing = false

# Functions configuration - completely disabled
# [functions]
#   directory = "netlify/functions"

# Redirects
[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/dashboard.html?user=admin"
  status = 200

[[redirects]]
  from = "/client"
  to = "/dashboard.html?user=client"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200